Baileylo\Blog\User\User:
  repositoryClass: Baileylo\Blog\User\Repository\DoctrineODM
  fields:
    id:
      type: id
      id: true
    name:
      type: string
    slug:
      type: string
      index: true
    email:
      type: string
    password:
      type: string
    rememberToken:
      type: string
      unique: true
