Baileylo\Blog\Page\Page:
  type: document
  lifecycleCallbacks:
    prePersist: [setCreatedAt]
    prePersist: [setUpdatedAt]
    preUpdate: [setUpdatedAt]
  indexes:
    slug:
      keys:
        slug: desc
      options:
        unique: true
        dropDups: true
        safe: true
  fields:
    id:
      type: id
      id: true
    isVisible:
      type: boolean
    createdAt:
      type: date
    updatedAt:
      type: date
    title:
      type: string
    slug:
      type: string
      index: true
    html:
      type: string



